### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by rameshpandy** [fbraem/mqweb#11]
I am using Redhat EL6 64 bit and when trying to make the mqweb using command ' make' it throws the below error.

Can you please help me to fix this.
````
QueueMapper.cpp
Linking MQWeb
/usr/bin/ld: skipping incompatible /usr/local/include/../lib/libPocoNetd.so when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/include/../lib/libPocoNetd.a when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib64/../lib/libPocoNetd.so when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib64/../lib/libPocoNetd.a when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib/../lib/libPocoNetd.so when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib/../lib/libPocoNetd.a when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib/libPocoNetd.so when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib/libPocoNetd.a when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib/libPocoNetd.so when searching for -lPocoNetd
/usr/bin/ld: skipping incompatible /usr/local/lib/libPocoNetd.a when searching for -lPocoNetd
/usr/bin/ld: cannot find -lPocoNetd
collect2: ld returned 1 exit status
make[1]: *** [../../bin/Debug/mqwebd] Error 1
make: *** [MQWeb] Error 2
[root@server1 gmake]#
````

**Comment by fbraem** [comment]
Did you run make with config=debug64 ?

**Comment by rameshpandy** [comment]
Thanks for your response. Yes, I have tried with this option and the output is

[root@devmql02 gmake]#  make config=debug64
==== Building MQ (debug64) ====
==== Building MQWeb (debug64) ====
Linking MQWeb
/usr/bin/ld: skipping incompatible ../../bin/Debug/libmqd.a when searching for -lmqd
/usr/bin/ld: cannot find -lmqd
collect2: ld returned 1 exit status
make[1]: *** [../../bin/Debug/mqwebd] Error 1
make: *** [MQWeb] Error 2
[root@devmql02 gmake]#

And I can find this file in the server
[root@devmql02 opt]# find . -name libmqd.a
./mqweb/mqweb-0.0.11/bin/Debug/libmqd.a

**Comment by fbraem** [comment]
"skipping incompatible" ... means you have build some libraries as 32 bit. I see you have the same warnings for Poco.

**Comment by fbraem** [comment]
You can check the type of libraries with:

objdump -f libmqd.a | grep ^architecture

This must show some lines with:

architecture: i386:x86-**64**, flags 0x00000011:

**Comment by rameshpandy** [comment]
Yes, seems it has build as 32-bit libraries. I could not find option to build 64 bit during Poco Build.
Please let me know the option to use in Poco build for 64 bit.

My OS is 
[root@devmql02 Debug]# uname -a
Linux devmql02 2.6.32-431.el6.x86_64 #1 SMP Thu Nov 21 13:35:52 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@devmql02 Debug]#


[root@devmql02 Debug]# ls
libmqd.a
[root@devmql02 Debug]# objdump -f libmqd.a | grep ^architecture
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
architecture: i386, flags 0x00000011:
[root@devmql02 Debug]#

**Comment by fbraem** [comment]
Can you show the ootput gcc -v? It should look like this:

````
] $ g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
````
You can also set the environment variable ````OSARCH_64BITS```` to 1. I have never done this, but in the POCO documentation it is mentioned :  _will force a 64 bit build on platforms that support 64 bit builds_

**Comment by rameshpandy** [comment]
Output of gcc and g++  

[root@devmql02 mqm]# gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=htt                                        p://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=re                                        lease --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enab                                        le-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib                                        /jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/sha                                        re/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i                                        686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC)


[root@devmql02 mqm]# g++ -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC)
[root@devmql02 mqm]#

**Comment by rameshpandy** [comment]
I have set the Env Variable OSARCH_64BITS to 1 and have compiled POCO again.

When I try to compile the MQWeb with debug64 option, I get the below error

[root@devmql02 gmake]# make clean
Cleaning MQ
Cleaning MQWeb
Cleaning MQCheck
Cleaning MQDictionary


[root@devmql02 gmake]# make config=debug64
==== Building MQ (debug64) ====
Linking MQ
==== Building MQWeb (debug64) ====
Linking MQWeb
obj/x64/Debug/MQWeb/MQMapper.o: In function `MQMapper':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:54: undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/x64/Debug/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::getReasonString(int)':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:71: undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:73: undefined reference to `MQ::Web::Dictionary::getDisplayValue(int, int) const'
obj/x64/Debug/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::getDisplayMap(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:83: undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/x64/Debug/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::addIntegerFilter()':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:117: undefined reference to `MQ::Web::Dictionary::getDisplayId(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
obj/x64/Debug/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::addParameterNumFromString(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:177: undefined reference to `MQ::Web::Dictionary::getDisplayId(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
obj/x64/Debug/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::execute(std::vector<Poco::SharedPtr<MQ::PCF, Poco::ReferenceCounter, Poco::ReleasePolicy<MQ::PCF> >, std::allocator<Poco::SharedPtr<MQ::PCF, Poco::ReferenceCounter, Poco::ReleasePolicy<MQ::PCF> > > >&)':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:205: undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:206: undefined reference to `MQ::Web::Dictionary::getDisplayValue(int, int) const'
obj/x64/Debug/MQWeb/MQMapper.o: In function `__static_initialization_and_destruction_0':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:31: undefined reference to `MQ::Web::DictionaryCache::DictionaryCache()'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:31: undefined reference to `MQ::Web::DictionaryCache::~DictionaryCache()'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::Dictionary()'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/x64/Debug/MQWeb/MQMapper.o:/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: more undefined references to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
obj/x64/Debug/MQWeb/MQMapper.o: In function `__static_initialization_and_destruction_0':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::~Dictionary()'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:47: undefined reference to `MQ::Web::Dictionary::~Dictionary()'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MQMapper.cpp:33: undefined reference to `MQ::Web::Dictionary::~Dictionary()'
obj/x64/Debug/MQWeb/MQMapper.o: In function `Dictionary':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/include/MQ/Web/Dictionary.h:28: undefined reference to `vtable for MQ::Web::Dictionary'
obj/x64/Debug/MQWeb/AuthenticationInformationMapper.o: In function `MQ::Web::MQMapper::createJSON(MQ::PCF const&)':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/include/MQ/Web/MQMapper.h:128: undefined reference to `MQ::Web::Dictionary::mapToJSON(MQ::PCF const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >&, bool) const'
obj/x64/Debug/MQWeb/MessageController.o: In function `MQ::Web::MessageController::event()':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MessageController.cpp:581: undefined reference to `MQ::Web::Dictionary::mapToJSON(MQ::PCF const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >&, bool) const'
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/src/MessageController.cpp:587: undefined reference to `MQ::Web::Dictionary::mapToJSON(MQ::PCF const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >&, bool) const'
obj/x64/Debug/MQWeb/MessageController.o: In function `MQ::Web::MQMapper::dictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/opt/mqweb/mqweb-0.0.11/build/gmake/../../MQWeb/include/MQ/Web/MQMapper.h:134: undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: ld returned 1 exit status
make[1]: *** [../../bin/Debug/mqwebd] Error 1
make: *** [MQWeb] Error 2
[root@devmql02 gmake]#

**Comment by rameshpandy** [comment]
Now the Library is 64 bit 
[root@devmql02 Debug]# ls -ltr
total 2956
-rw-r--r-- 1 root root 3025814 Jan 27 12:11 libmqd.a
[root@devmql02 Debug]# objdump -f libmqd.a | grep ^architecture
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
architecture: i386:x86-64, flags 0x00000011:
[root@devmql02 Debug]#

**Comment by fbraem** [comment]
Weird. I've build POCO and MQWeb on almost the same environment without any problem.

````
$ gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)
````
Can you see if there are any -m32 arguments in the generated makefiles of POCO and MQWeb?

**Comment by rameshpandy** [comment]
Yes, I can see the .m32 arguments 

[root@devmql02 gmake]# grep m32 *
MQCheck.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
MQCheck.make:  LDFLAGS   += -m32 -L/usr/lib32 -L../../bin/Debug -L/usr/local/include/lib
MQCheck.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -m32
MQCheck.make:  LDFLAGS   += -s -m32 -L/usr/lib32 -L../../bin/Release -L/usr/local/include/lib
MQDictionary.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
MQDictionary.make:  LDFLAGS   += -m32 -L/usr/lib32 -L../../bin/Debug -L/usr/local/include/usr/local/lib -L../../bin/Debug
MQDictionary.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -m32
MQDictionary.make:  LDFLAGS   += -s -m32 -L/usr/lib32 -L../../bin/Release -L/usr/local/include/usr/local/lib -L../../bin/Debug
MQ.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
MQ.make:  LDFLAGS   += -m32 -L/usr/lib32 -L../../bin/Debug
MQ.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -m32
MQ.make:  LDFLAGS   += -s -m32 -L/usr/lib32 -L../../bin/Release
MQWeb.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
MQWeb.make:  LDFLAGS   += -m32 -L/usr/lib32 -L../../bin/Debug -L/usr/local/include/usr/local/lib
MQWeb.make:  CFLAGS    += $(CPPFLAGS) $(ARCH) -m32
MQWeb.make:  LDFLAGS   += -s -m32 -L/usr/lib32 -L../../bin/Release -L/usr/local/include/usr/local/lib
[root@devmql02 gmake]# pwd
/opt/mqweb/mqweb-0.0.11/build/gmake
[root@devmql02 gmake]#

But m32 arguments not found in POCO Build

[root@devmql02 poco-1.6.0-all]# pwd
/opt/mqweb/poco-1.6.0-all
[root@devmql02 poco-1.6.0-all]# grep m32 *

**Comment by rameshpandy** [comment]
I have checked the MQWeb Build make files, I can see -m64 only under debug64 and release64 tag, so I think this should be fine.

**Comment by fbraem** [comment]
Can you remove the folder  ````mqweb-0.0.11/build/gmake/obj```` and then run ````make config=debug64```` again? It seems that this isn't cleaned up when running make clean. I've tried to build mqweb from the 0.0.11 archive also and this is my output:

````
$ make config=debug64
==== Building MQ (debug64) ====
Creating ../../bin/Debug
Creating obj/x64/Debug/MQ
MQSubsystem.cpp
CommandServer.cpp
MQFunctions.cpp
QueueManager.cpp
PCF.cpp
MQException.cpp
QueueManagerPool.cpp
Message.cpp
Queue.cpp
Linking MQ
==== Building MQWeb (debug64) ====
Creating obj/x64/Debug/MQWeb
Controller.cpp
QueueStatusMapper.cpp
AuthorityRecordController.cpp
JSONView.cpp
QueueMapper.cpp
QueueManagerController.cpp
DictionaryCache.cpp
QueueManagerStatusMapper.cpp
ProcessController.cpp
ListenerController.cpp
ClusterQueueManagerController.cpp
MQMapper.cpp
StaticRequestHandler.cpp
MQController.cpp
ListenerStatusMapper.cpp
QueueManagerPoolCache.cpp
TemplateView.cpp
Dictionary.cpp
ListenerStatusController.cpp
ListenerMapper.cpp
QueueStatusController.cpp
JSONPView.cpp
View.cpp
QueueManagerMapper.cpp
ChannelStatusMapper.cpp
MessageController.cpp
QueueManagerStatusController.cpp
NamelistMapper.cpp
ConnectionMapper.cpp
ControllerRequestHandler.cpp
NamelistController.cpp
ServiceController.cpp
ConnectionController.cpp
DenyRequestHandler.cpp
ChannelMapper.cpp
WebController.cpp
ServiceMapper.cpp
ClusterQueueManagerMapper.cpp
QueueController.cpp
RequestHandlerFactory.cpp
AuthorityRecordMapper.cpp
MultiView.cpp
Application.cpp
ChannelStatusController.cpp
AuthenticationInformationMapper.cpp
AuthenticationInformationController.cpp
ChannelController.cpp
ProcessMapper.cpp
Linking MQWeb
==== Building MQCheck (debug64) ====
Creating obj/x64/Debug/MQCheck
Application.cpp
../../MQCheck/src/Application.cpp: In member function ‘virtual int MQCheckApplication::main(const std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
../../MQCheck/src/Application.cpp:131: error: no matching function for call to ‘MQ::CommandServer::CommandServer(MQ::QueueManager::Ptr&, const char [27])’
../../MQ/include/MQ/CommandServer.h:58: note: candidates are: MQ::CommandServer::CommandServer(const MQ::CommandServer&)
../../MQ/include/MQ/CommandServer.h:55: note:                 MQ::CommandServer::CommandServer(MQ::QueueManager&, const std::string&)
make[1]: *** [obj/x64/Debug/MQCheck/Application.o] Error 1
make: *** [MQCheck] Error 2
````
The MQCheck error can be ignored, because it is a sample program (the problem will be fixed in 0.0.12).

**Comment by rameshpandy** [comment]
Tried the same, still no luck. Can you please provide the compiled binaries so that I can directly put those in a directory and run it. 

[root@devmql02 build]# rm -rf gmake
[root@devmql02 build]# pwd
/opt/mqweb/mqweb-0.0.11/build
[root@devmql02 build]# cd ../
[root@devmql02 mqweb-0.0.11]# ls
bin    ChangeLog.txt  MQ       MQDictionary  MQWeb      premake4.lua       samples  templates
build  license.txt    MQCheck  mq.lua        poco.lua  premake4      README.md         static   test
[root@devmql02 mqweb-0.0.11]# ./premake4 gmake
Trying to find POCO ourselves ...
If this is not what you want, set the poco_dir variable in poco.lua and run again.
Ok.
Poco Include Directory: /usr/local/include
Poco Library Directory: /usr/local/lib
Building configurations...
Running action 'gmake'...
Generating build/gmake/Makefile...
Generating build/gmake/MQ.make...
Generating build/gmake/MQWeb.make...
Generating build/gmake/MQCheck.make...
Generating build/gmake/MQDictionary.make...
Done.
[root@devmql02 mqweb-0.0.11]# cd build/gmake
[root@devmql02 gmake]# make config=release64
==== Building MQ (release64) ====
Creating obj/x64/Release/MQ
MQFunctions.cpp
PCF.cpp
CommandServer.cpp
Queue.cpp
QueueManagerPool.cpp
QueueManager.cpp
MQSubsystem.cpp
MQException.cpp
Message.cpp
Linking MQ
==== Building MQWeb (release64) ====
Creating obj/x64/Release/MQWeb
AuthenticationInformationController.cpp
MQMapper.cpp
AuthenticationInformationMapper.cpp
ListenerMapper.cpp
QueueStatusController.cpp
WebController.cpp
RequestHandlerFactory.cpp
MessageController.cpp
QueueStatusMapper.cpp
QueueManagerMapper.cpp
View.cpp
TemplateView.cpp
ConnectionController.cpp
NamelistMapper.cpp
MultiView.cpp
ListenerStatusMapper.cpp
QueueController.cpp
AuthorityRecordController.cpp
ChannelController.cpp
Controller.cpp
ProcessController.cpp
QueueManagerPoolCache.cpp
JSONView.cpp
NamelistController.cpp
MQController.cpp
ChannelStatusController.cpp
ServiceMapper.cpp
Application.cpp
ConnectionMapper.cpp
StaticRequestHandler.cpp
QueueManagerStatusController.cpp
ServiceController.cpp
ControllerRequestHandler.cpp
ClusterQueueManagerController.cpp
ClusterQueueManagerMapper.cpp
ChannelMapper.cpp
AuthorityRecordMapper.cpp
ListenerController.cpp
QueueManagerController.cpp
QueueManagerStatusMapper.cpp
ListenerStatusController.cpp
JSONPView.cpp
ChannelStatusMapper.cpp
DenyRequestHandler.cpp
ProcessMapper.cpp
QueueMapper.cpp
Linking MQWeb
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::MQMapper(MQ::CommandServer&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >)':
MQMapper.cpp:(.text+0x86): undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::getReasonString(int)':
MQMapper.cpp:(.text+0x3d1): undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
MQMapper.cpp:(.text+0x48a): undefined reference to `MQ::Web::Dictionary::getDisplayValue(int, int) const'
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::getDisplayMap(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
MQMapper.cpp:(.text+0x4e3): undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::addIntegerFilter()':
MQMapper.cpp:(.text+0xbbc): undefined reference to `MQ::Web::Dictionary::getDisplayId(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::addParameterNumFromString(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
MQMapper.cpp:(.text+0x1631): undefined reference to `MQ::Web::Dictionary::getDisplayId(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::MQMapper::execute(std::vector<Poco::SharedPtr<MQ::PCF, Poco::ReferenceCounter, Poco::ReleasePolicy<MQ::PCF> >, std::allocator<Poco::SharedPtr<MQ::PCF, Poco::ReferenceCounter, Poco::ReleasePolicy<MQ::PCF> > > >&)':
MQMapper.cpp:(.text+0x1861): undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
MQMapper.cpp:(.text+0x193c): undefined reference to `MQ::Web::Dictionary::getDisplayValue(int, int) const'
obj/x64/Release/MQWeb/MQMapper.o: In function `__static_initialization_and_destruction_0(int, int)':
MQMapper.cpp:(.text+0x1ae0): undefined reference to `MQ::Web::DictionaryCache::DictionaryCache()'
MQMapper.cpp:(.text+0x1ae5): undefined reference to `MQ::Web::DictionaryCache::~DictionaryCache()'
MQMapper.cpp:(.text+0x1d52): undefined reference to `MQ::Web::Dictionary::Dictionary()'
MQMapper.cpp:(.text+0x1d6d): undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
MQMapper.cpp:(.text+0x1d81): undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
MQMapper.cpp:(.text+0x1d95): undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
MQMapper.cpp:(.text+0x1da9): undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
MQMapper.cpp:(.text+0x1dbd): undefined reference to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
obj/x64/Release/MQWeb/MQMapper.o:MQMapper.cpp:(.text+0x1dd1): more undefined references to `MQ::Web::Dictionary::operator()(int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
obj/x64/Release/MQWeb/MQMapper.o: In function `__static_initialization_and_destruction_0(int, int)':
MQMapper.cpp:(.text+0x1e94): undefined reference to `MQ::Web::Dictionary::~Dictionary()'
MQMapper.cpp:(.text+0x1eab): undefined reference to `MQ::Web::Dictionary::~Dictionary()'
MQMapper.cpp:(.text+0x236e): undefined reference to `MQ::Web::Dictionary::~Dictionary()'
obj/x64/Release/MQWeb/MQMapper.o: In function `MQ::Web::Dictionary::Dictionary(MQ::Web::Dictionary const&)':
MQMapper.cpp:(.text._ZN2MQ3Web10DictionaryC2ERKS1_[_ZN2MQ3Web10DictionaryC5ERKS1_]+0x1a): undefined reference to `vtable for MQ::Web::Dictionary'
obj/x64/Release/MQWeb/AuthenticationInformationMapper.o: In function `MQ::Web::MQMapper::createJSON(MQ::PCF const&)':
AuthenticationInformationMapper.cpp:(.text._ZN2MQ3Web8MQMapper10createJSONERKNS_3PCFE[MQ::Web::MQMapper::createJSON(MQ::PCF const&)]+0x86): undefined reference to `MQ::Web::Dictionary::mapToJSON(MQ::PCF const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >&, bool) const'
obj/x64/Release/MQWeb/MessageController.o: In function `MQ::Web::MessageController::event()':
MessageController.cpp:(.text+0x4a09): undefined reference to `MQ::Web::Dictionary::mapToJSON(MQ::PCF const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >&, bool) const'
MessageController.cpp:(.text+0x4b07): undefined reference to `MQ::Web::Dictionary::mapToJSON(MQ::PCF const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object> >&, bool) const'
obj/x64/Release/MQWeb/MessageController.o: In function `MQ::Web::MQMapper::dictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
MessageController.cpp:(.text._ZN2MQ3Web8MQMapper10dictionaryERKSs[MQ::Web::MQMapper::dictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)]+0x20): undefined reference to `MQ::Web::DictionaryCache::getDictionary(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: ld returned 1 exit status
make[1]: *** [../../bin/Release/mqweb] Error 1
make: *** [MQWeb] Error 2
[root@devmql02 gmake]#

**Comment by fbraem** [comment]
It's weird that your output doesn't show that it has build Dictionary.cpp and DictionaryCache.cpp ... Can you see that these files are part of MQWeb.make?

**Comment by fbraem** [comment]
I've attached an archive with the binaries on the release ...

**Comment by rameshpandy** [comment]
It is not part of MQWeb.make, I could find it in MQDictionary.make.

I could not locate the binaries. Can you please give me the release and folder.

[root@devmql02 gmake]# grep -i dict *
Makefile:PROJECTS := MQ MQWeb MQCheck MQDictionary
Makefile:MQDictionary:
Makefile:       @echo "==== Building MQDictionary ($(config)) ===="
Makefile:       @${MAKE} --no-print-directory -C . -f MQDictionary.make
Makefile:       @${MAKE} --no-print-directory -C . -f MQDictionary.make clean
Makefile:       @echo "   MQDictionary"
MQDictionary.make:  OBJDIR     = obj/x32/Debug/MQDictionary
MQDictionary.make:  TARGET     = $(TARGETDIR)/mqdictd
MQDictionary.make:  OBJDIR     = obj/x32/Release/MQDictionary
MQDictionary.make:  TARGET     = $(TARGETDIR)/mqdict
MQDictionary.make:  OBJDIR     = obj/x64/Debug/MQDictionary
MQDictionary.make:  TARGET     = $(TARGETDIR)/mqdictd
MQDictionary.make:  OBJDIR     = obj/x64/Release/MQDictionary
MQDictionary.make:  TARGET     = $(TARGETDIR)/mqdict
MQDictionary.make:      $(OBJDIR)/Dictionary.o \
MQDictionary.make:      @echo Linking MQDictionary
MQDictionary.make:      @echo Cleaning MQDictionary
MQDictionary.make:$(OBJDIR)/Application.o: ../../MQDictionary/src/Application.cpp
MQDictionary.make:$(OBJDIR)/Dictionary.o: ../../MQWeb/src/Dictionary.cpp
[root@devmql02 gmake]#

**Comment by fbraem** [comment]
Dictionary and DictionaryCache must also be part of the MQWeb build ... I don't understand why they are not included in your generated makefile.

You can find the binaries here: https://github.com/fbraem/mqweb/releases/download/v0.0.11/mqweb.x86_64.tar.gz

**Comment by rameshpandy** [comment]
Shall I use any other version to check this. I have downloaded the Release - mqweb-0.0.11

**Comment by fbraem** [comment]
I've done the same as you with a downloaded version of release 0.0.11 and build it on a clean Red Hat without any problems. Which version of premake4 do you use? I use version 4.3.
