### ISSUE TITLE
Ebcdic fonction not working 

### ISSUE THREAD

**Issue by botrem0011** [fbraem/mqweb#13]
show ascii is working with old static (mqweb 0.10)
show ebcdic not working, data empty

**Comment by fbraem** [comment]
Can you try the latest version? 
Note: ebcdic property is removed in this version, because the hex property shows the data without conversion in hex format,. When the ccsid = 500, the ascii property will contain ebcdic characters which are translated to ascii characters.

**Comment by botrem0011** [comment]
I tried with the latest version 0.0.12.
In the messages, we have ebcdic codes that can not be translated and with mix of both.
Actually we use mqweb 0.10, is simplest and it's not depending of ccsid ...

**Comment by fbraem** [comment]
Can you give me an example of a character (code) that can't be displayed?

**Comment by botrem0011** [comment]
We use messages MQ between zOs programs. In several cases, we write entire record (copy area) to message and record contains alphanumeric fields and comp-3 fields. Comp fields cannot be displayed as a simple chars ...

**Comment by fbraem** [comment]
After some debugging (the develop branch) I noticed a problem with using char instead of unsigned char to get the ascii character from the EBCDIC table. This will be fixed in the development branch.
