### ISSUE TITLE
Read MQ-command-events and MQ-config-events on the nodes?

### ISSUE THREAD

**Issue by maartenszeker** [fbraem/mqweb#14]
Hey fbraem,

I'm pretty new to all this but i'm sure you are able to provide us (me and my collegues) with the right questions to understand the content of the following "enhancement-request".

Would it be a good idea to collect (MQGET) the native WSMQ-"audit/error/..."-events that are generated on WSMQ-backends in MQWEB. (as you are probably well aware those messages have a pcf-structure)

What is your idea as an expert on the following usecases?

e.g.:
- One might be able to see in MQWEB who execute an administrative action (stop channel/refresh security/resume cluster/define object/...) and when (via "WSMQ command events" that are generated on the connected MQ-nodes)
- One might be able to see in MQWEB who changed/defined an MQ-object + what was the object definition BEFORE and AFTER that action (via "WSMQ config events" that are generated on the connected MQ-nodes)
  (A same mechanism could be implemented for "qmgr-event-queues" and several other event-queues. However I'm not sure whether this will result in too much content for one enhancement request...)

In this proposal MQWEB would destructively read the messages on the connected WSMQ-nodes on the configured audit-event-queues. ("command-events" and "config-events")
If supporting other "event-consumers of the same audit/error-events" is a requirement, it will be possible to archieve this via PUB/SUB-setup on the MQ-queuemanager. The suggested mechanism of MQGET may ensure that audit-events can be read in a swift and performing manner (mqget with wait-interval) and the "MQGET by MQWEB" does not need to result in a loss of audit/error-information.

**Comment by fbraem** [comment]
Hi Maarten,

Viewing events with MQWeb is already possible with [/api/message/event](http://www.mqweb.org/api/message.html). Currently this is only tested with the queue SYSTEM.ADMIN.QGMR.EVENT, but adding all the other event queues can be done (it's a matter of testing and adding the MQ attributes that are missing).

Comparing the before/after events: I'm not sure that this functionality should be part of the MQWeb daemon. A script can be used to call [/api/message/event](http://www.mqweb.org/api/message.html) and do the compare. Would be nice to create a sample script for this ...

Reading (event) messages should be possible with browse or get. I think it's up to the script developer to decide if a message is read destructively or not.

**Comment by fbraem** [comment]
Browsing event messages is available in version 0.1.00

**Comment by maartenszeker** [comment]
Nice enhancement!
